//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Application.Localization {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class SystemMessages {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal SystemMessages() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Application.Localization.SystemMessages", typeof(SystemMessages).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A user with this email already exists..
        /// </summary>
        public static string EmailAlreadyExists {
            get {
                return ResourceManager.GetString("EmailAlreadyExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An internal server error occurred..
        /// </summary>
        public static string InternalServerError {
            get {
                return ResourceManager.GetString("InternalServerError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid email or password..
        /// </summary>
        public static string InvalidCredentials {
            get {
                return ResourceManager.GetString("InvalidCredentials", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The password does not meet security requirements..
        /// </summary>
        public static string PasswordTooWeak {
            get {
                return ResourceManager.GetString("PasswordTooWeak", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to You must select at least one playlist with tracks..
        /// </summary>
        public static string AtLeastOnePlaylistRequired {
            get {
                return ResourceManager.GetString("AtLeastOnePlaylistRequired", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Destination playlist was not created..
        /// </summary>
        public static string DestinationPlaylistWasNotCreated {
            get {
                return ResourceManager.GetString("DestinationPlaylistWasNotCreated", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Selected playlists do not contain tracks..
        /// </summary>
        public static string SelectedPlaylistsContainNoTracks {
            get {
                return ResourceManager.GetString("SelectedPlaylistsContainNoTracks", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Track was not found on destination platform..
        /// </summary>
        public static string TrackWasNotFoundOnDestinationPlatform {
            get {
                return ResourceManager.GetString("TrackWasNotFoundOnDestinationPlatform", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Transfer creation failed..
        /// </summary>
        public static string TransferCreationFailed {
            get {
                return ResourceManager.GetString("TransferCreationFailed", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Transfer execution failed..
        /// </summary>
        public static string TransferExecutionFailed {
            get {
                return ResourceManager.GetString("TransferExecutionFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User is not connected to {0}..
        /// </summary>
        public static string UserNotConnected {
            get {
                return ResourceManager.GetString("UserNotConnected", resourceCulture);
            }
        }
    }
}
